### ISSUE TITLE
More PHP related talks

### ISSUE THREAD

**Issue by neonichu** [swissmobidevs/appbuilders16#14]
Seems like @bontoJR is [already on it](https://twitter.com/bontoJR/status/725243817981566976), but I just want to emphasise this again.

![](https://pbs.twimg.com/media/ChCVaBuWUAACFEP.jpg)

**Comment by bontoJR** [comment]
I don't even know if I should ban you or just smile... I think I am going just to smile (while banning you) :trollface:

**Comment by neonichu** [comment]
:sob:
