### ISSUE TITLE
Attendee Food Preferences

### ISSUE THREAD

**Issue by simonayzman** [swissmobidevs/appbuilders16#25]
Some sort of option to give food preferences (perhaps during registration) might have been useful. For example, I couldn't eat any bread or bread products this week for Passover, so I basically couldn't eat any of the lunches. This issue also applies to people who are vegetarians, halal, gluten-free, etc.

**Comment by BalestraPatrick** [comment]
Hey, thanks for the feedback!
I personally contacted all the attendees + speakers one week before the conference if during the registration the answered "yes" to the question whether or not they had an allergy or preference. 
I am really sorry about this, next time we will consider adding more choices and exactly tell everyone in advance what the food at the conference will be. In this way we can find a solution for everyone 👍

**Comment by simonayzman** [comment]
Apologies! I must've overlooked the flag/message.

**Comment by bontoJR** [comment]
Let's keep this open, next year we will have to consider all potential preferences. 👍 
A good example is how Airlines are doing, asking for detailed preference and ask if there's any extra allergy. I would not put all the preferences, but at least the most common one:
- Vegetarian
- Vegan
- Gluten intolerant
- Diabetic

These 4 are the most common ones on Airlines, so we can avoid any kind of issues. The venue would not have extra option considering is out of the city and part of an University Campus :)

**Comment by elyl3d** [comment]
Hi! I received the registration form asking me for food allergies/preferences and I wrote "vegan", so I was pretty excited about it 💃  and during those two days they did not offered vegan food at all 👎  :( I ate somewhere else. That's a shame, since I could have taken something with me otherwise. 

I am glad that now you know for the following years 👍  :)  

:)

**Comment by bontoJR** [comment]
@elymer sorry about that, we explicitly asked for Vegan options to our catering, which obviously ignored our requests. We are going to be more explicit in our requests the next time and make sure everybody is going to have food which has to be covered by us.
